/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObrigadoNr1RouteImport } from './routes/obrigado-nr1'
import { Route as Nr1SaudeMentalCorporativaRouteImport } from './routes/nr1-saude-mental-corporativa'
import { Route as LpNr1SaudeMentalCorporativaRouteImport } from './routes/lp-nr1-saude-mental-corporativa'
import { Route as IndexRouteImport } from './routes/index'

const ObrigadoNr1Route = ObrigadoNr1RouteImport.update({
  id: '/obrigado-nr1',
  path: '/obrigado-nr1',
  getParentRoute: () => rootRouteImport,
} as any)
const Nr1SaudeMentalCorporativaRoute =
  Nr1SaudeMentalCorporativaRouteImport.update({
    id: '/nr1-saude-mental-corporativa',
    path: '/nr1-saude-mental-corporativa',
    getParentRoute: () => rootRouteImport,
  } as any)
const LpNr1SaudeMentalCorporativaRoute =
  LpNr1SaudeMentalCorporativaRouteImport.update({
    id: '/lp-nr1-saude-mental-corporativa',
    path: '/lp-nr1-saude-mental-corporativa',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lp-nr1-saude-mental-corporativa': typeof LpNr1SaudeMentalCorporativaRoute
  '/nr1-saude-mental-corporativa': typeof Nr1SaudeMentalCorporativaRoute
  '/obrigado-nr1': typeof ObrigadoNr1Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lp-nr1-saude-mental-corporativa': typeof LpNr1SaudeMentalCorporativaRoute
  '/nr1-saude-mental-corporativa': typeof Nr1SaudeMentalCorporativaRoute
  '/obrigado-nr1': typeof ObrigadoNr1Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lp-nr1-saude-mental-corporativa': typeof LpNr1SaudeMentalCorporativaRoute
  '/nr1-saude-mental-corporativa': typeof Nr1SaudeMentalCorporativaRoute
  '/obrigado-nr1': typeof ObrigadoNr1Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lp-nr1-saude-mental-corporativa'
    | '/nr1-saude-mental-corporativa'
    | '/obrigado-nr1'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lp-nr1-saude-mental-corporativa'
    | '/nr1-saude-mental-corporativa'
    | '/obrigado-nr1'
  id:
    | '__root__'
    | '/'
    | '/lp-nr1-saude-mental-corporativa'
    | '/nr1-saude-mental-corporativa'
    | '/obrigado-nr1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LpNr1SaudeMentalCorporativaRoute: typeof LpNr1SaudeMentalCorporativaRoute
  Nr1SaudeMentalCorporativaRoute: typeof Nr1SaudeMentalCorporativaRoute
  ObrigadoNr1Route: typeof ObrigadoNr1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/obrigado-nr1': {
      id: '/obrigado-nr1'
      path: '/obrigado-nr1'
      fullPath: '/obrigado-nr1'
      preLoaderRoute: typeof ObrigadoNr1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nr1-saude-mental-corporativa': {
      id: '/nr1-saude-mental-corporativa'
      path: '/nr1-saude-mental-corporativa'
      fullPath: '/nr1-saude-mental-corporativa'
      preLoaderRoute: typeof Nr1SaudeMentalCorporativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp-nr1-saude-mental-corporativa': {
      id: '/lp-nr1-saude-mental-corporativa'
      path: '/lp-nr1-saude-mental-corporativa'
      fullPath: '/lp-nr1-saude-mental-corporativa'
      preLoaderRoute: typeof LpNr1SaudeMentalCorporativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LpNr1SaudeMentalCorporativaRoute: LpNr1SaudeMentalCorporativaRoute,
  Nr1SaudeMentalCorporativaRoute: Nr1SaudeMentalCorporativaRoute,
  ObrigadoNr1Route: ObrigadoNr1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
